services:
  yolo:
    image: ${YOLO_IMG_NAME}
    restart: always
    ports:
      - "8081:8081"
    env_file: .env
    networks:
      - observability
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.98.0  # replace latest with a pinned version
    command: ["--config", "/etc/otelcol/config.yaml"]
    ports:
      - "8889:8889"
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol/config.yaml
      - /proc:/host_proc:ro
      - /sys:/host_sys:ro
    environment:
      - HOST_PROC=/host_proc
      - HOST_SYS=/host_sys
    network_mode: host  # required for host metrics

networks:
  observability:
