receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'yolo'
          static_configs:
            - targets: ['yolo:8081']

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheus]
