receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'yolo'
          metrics_path: /metrics
          static_configs:
            - targets: ['yolo:8081']

  hostmetrics:
    collection_interval: 10s
    root_path: /host_proc
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      load:
      network:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [prometheus, hostmetrics]
      exporters: [prometheus]
