name: Yolo Build Dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.save-image.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/yolo-dev:${{ github.run_number }}
          echo "🔧 Building base image (original)"
          docker build -t $BASE_IMAGE .
      
          echo "🔧 Creating patched Dockerfile with curl"
          echo "FROM $BASE_IMAGE" > Dockerfile.patched
          echo "RUN apt-get update && apt-get install -y curl" >> Dockerfile.patched
      
          echo "🔧 Building final image with curl: $IMAGE_NAME"
          docker build -t $IMAGE_NAME -f Dockerfile.patched .
      
          echo "📤 Pushing final image to DockerHub"
          docker push $IMAGE_NAME
      
          echo "$IMAGE_NAME" > image_name.txt
          
          # Save to file for artifact
          echo "$IMAGE_NAME" > image_name.txt


      - name: Save image name as output
        id: save-image
        run: |
          IMAGE_NAME=$(cat image_name.txt)
          echo "image=$IMAGE_NAME" >> "$GITHUB_OUTPUT"
          echo "✅ Saved image output: $IMAGE_NAME"

      - name: Upload image name as artifact
        uses: actions/upload-artifact@v4
        with:
          name: yolo-image-name
          path: image_name.txt

  deploy:
    needs: build
    uses: merryshalabi/YoloService/.github/workflows/deployment-dev.yaml@dev  # ✅ Use full repo path and branch
    with:
      image: ${{ needs.build.outputs.image }}
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      EC2_HOST_DEV: ${{ secrets.EC2_HOST_DEV }}
      S3_BUCKET_NAME_DEV: ${{ secrets.S3_BUCKET_NAME_DEV }}
