name: YOLO Test and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH access to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

      - name: Copy repo to EC2 and run tests
        run: |
          scp -r . ubuntu@$EC2_HOST:~/YoloService
          ssh ubuntu@$EC2_HOST '
            cd ~/YoloService &&
            chmod +x setup.sh &&
            ./setup.sh &&
            source .venv/bin/activate &&
            python3 -m unittest discover -s tests -v
          '

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy YOLO to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

          scp -r . ubuntu@$EC2_HOST:~/YoloService
          ssh ubuntu@$EC2_HOST '
            cd ~/YoloService &&
            chmod +x setup.sh &&
            ./setup.sh
          '