name: Yolo Test and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

      - name: Prepare and test on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_HOST '
            set -e
            cd ~
            if [ -d "YoloService" ]; then
              cd YoloService
              git pull
            else
              git clone https://github.com/${{ github.repository }}.git YoloService
              cd YoloService
            fi

            if [ ! -d ".venv" ]; then
              python3 -m venv .venv
            fi

            source .venv/bin/activate
            pip install --upgrade pip

            if [ -f "requirements.txt" ]; then
              pip install -r requirements.txt
            fi

            if [ -f "torch-requirements.txt" ]; then
              pip install -r torch-requirements.txt
            fi

            echo "Running unit tests..."
            python3 -m unittest discover -s tests -v
          '

      - name: Deploy yolo.service
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$EC2_HOST '
            set -e
            cd ~/YoloService

            echo "Copying and restarting yolo.service"
            sudo cp yolo.service /etc/systemd/system/yolo.service
            sudo systemctl daemon-reload
            sudo systemctl restart yolo.service
            sudo systemctl enable yolo.service

            if ! systemctl is-active --quiet yolo.service; then
              echo "❌ yolo.service is not running."
              sudo systemctl status yolo.service --no-pager
              exit 1
            fi

            echo "✅ yolo.service is active and running."
          '